//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.BorrowedBooks = new HashSet<BorrowedBooks>();
            this.Stock = new HashSet<Stock>();
        }
    
        public int book_id { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public string description { get; set; }
        public System.DateTime publish_date { get; set; }
        public string editorial { get; set; }
        public string edicion { get; set; }
        public bool best_seller { get; set; }
        public int category_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public int creation_user { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowedBooks> BorrowedBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
